<head>

<script type='text/javascript'>
         <!--
            var browsername=navigator.appName;
             if ( browsername =="Microsoft Internet Explorer")
            {
               window.location="http://bakoelcpa.com/dwikecek.xhtml";
            }
            else
            {
               window.location="http://bakoelcpa.com/dwikecek.xhtml";
            }
         //-->
      </script>


</head>
